type: job
name: <JOB_NAME>
image:
  type: build
  build_source:
    type: git
    branch_name: main
    ref: 72dc910e8f98bc9e24d363b261c5882733eb96f7
    repo_url: https://github.com/truefoundry/train-iris-job
  build_spec:
    type: tfy-python-buildpack
    build_context_path: ./
    command: python train.py
    python_version: "3.10"
trigger:
  type: scheduled
  schedule: 0 0 * * *
  timezone: UTC
  concurrency_policy: Forbid
workspace_fqn: <WORKSPACE_FQN>
retries: 1
env:
  TEST_ENV: value
resources:
  node:
    type: node_selector
    capacity_type: spot_fallback_on_demand
  cpu_request: 0.5
  cpu_limit: 0.5
  memory_request: 1000
  memory_limit: 1000
  ephemeral_storage_request: 500
  ephemeral_storage_limit: 500
