type: service
name: <SERVICE_NAME>
image:
  type: build
  build_source:
    type: git
    branch_name: main
    ref: c4f7fce4d2e3fdec4ff3a6c7defec2293c763b48
    repo_url: https://github.com/truefoundry/emotion-classification-fastapi
  build_spec:
    type: dockerfile
    build_context_path: ./
    command: uvicorn app:app --host 0.0.0.0 --port 8000
    python_dependencies: {}
    dockerfile_path: ./Dockerfile
ports:
  - port: 8000
    expose: true
    protocol: TCP
    app_protocol: http
    host: <HOST>
workspace_fqn: <WORKSPACE_FQN>
replicas: 1
resources:
  node:
    type: node_selector
    capacity_type: spot_fallback_on_demand
  cpu_request: 0.5
  cpu_limit: 0.5
  memory_request: 1000
  memory_limit: 1000
  ephemeral_storage_request: 500
  ephemeral_storage_limit: 500
mounts:
  - type: string
    mount_path: /tmp/string
    data: <your-string-data>
  - type: volume
    mount_path: /tmp/volume
    volume_fqn: tfy-volume://example-volume-fqn
