name: Apply Cluster Configuration

on:
  push:
    branches:
      - main
      - md_update_github_action_to_use_tfy_apply_on_directory
    paths:
      - "**/*.yaml"
      - "**/*.yml"
    paths-ignore:
      - ".github/workflows/**"

jobs:
  apply-cluster-config:
    runs-on: ubuntu-latest
    env:
      TFY_API_KEY: ${{ secrets.TFY_API_KEY }}
      TFY_HOST: ${{ secrets.TFY_HOST }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup TFY CLI
        run: pip install -U "truefoundry==0.14.0rc.1"

      - name: Apply changed manifests
        run: |
          set -euo pipefail
          rm -rf .github/workflows
          tfy apply -d . --diffs-only --ref "${{ github.event.before }}"
